In [3]:
import numpy as np

In [4]:
# 넘파이 ndarray 클래스 생성 1
ar = np.array([0,1,2,3,4,5,6,7,8,9])
type(ar)

numpy.ndarray

In [5]:
# 넘파이 ndarray 클래스 생성 2
arr = np.arange(10)
arr
type(arr)

# ndarray 배열 객체는 리스트와 유사해보이지만, 하나의 통일된 자료형으로만 배열을 구상해야하는 차이가 있다.

numpy.ndarray

In [6]:
# 리스트 객체 원소 연산법
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = []
for di in data:
    answer.append(2*di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [7]:
# 배열 객체 원소 연산법
#x = np.arange(10)
x = np.array(data)
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# 리스트 객체에서 배열 연산과 같이 한다면? => 객체의 크기가 정수배만큼 증가한다.
answer*2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [10]:
# ndarray 연산
2*a+b # array([12, 24, 36])
a == 2 # array([False,  True, False])
b > 10 # array([False,  True,  True])
(a == 2) & (b > 10) # array([False,  True, False])


array([False,  True, False])

In [11]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
# 행 / 열
len(c), len(c[0])

(2, 3)

In [13]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [14]:
# depth, row, column
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [15]:
# 배열의 차원
d.ndim # 3
d.shape # (2, 3, 4)

(2, 3, 4)

In [16]:
d[0,0:2, 1:3]


array([[2, 3],
       [6, 7]])

In [17]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [18]:
# 7을 인덱싱하기
m[1,2]

# 14 인덱싱
m[2,-1]
 
# [6,7] 인덱싱
m[1,1:3]

# [7,12] 인덱싱
m[1:3, 2]

# [[3,4],[8,9]] 인덱싱
m[0:2, 3:5]

array([[3, 4],
       [8, 9]])

In [19]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [20]:
# Index array : 특정 배열의 원소들 추출할 때, 인덱스의 TF를 사용하여 추출할 수 있음
a % 2


array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [21]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [22]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [23]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]
# 같은 원소를 반복해서 가리키는 경우에는 배열 인덱스가 원래의 배열보다 더 커지기도 한다.

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [24]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [26]:
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [27]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
#1. 3의 배수를 모두 찾아라
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [33]:
#2. 4로 나누면 1이 남는 수를 찾아라.
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [34]:
#3. 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x%3==0)&(x%4==1)]

array([9])