### Numpy 자료형
- 배열 생성 시 dtype을 통해 명시하지 않으면, 스스로 유추함
    1. 'b' : boolean
    2. 'i' : 정수
    3. 'u' : 부호없는 정수
    4. 'f' : float
    5. 'O' : 객체
    6. 'S' : 바이트 문자열
    7. 'U' : 유니코드 문자열

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x.dtype

dtype('int32')

In [3]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [4]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [8]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [9]:
x[0] + x[1]

3.0

In [10]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [11]:
x[0] + x[1]

'12'

In [12]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\wooju\AppData\Local\Temp\ipykernel_25524\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\wooju\AppData\Local\Temp\ipykernel_25524\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

### 배열 생성

In [20]:
# 영행렬 : 모든 값이 0으로 초기화된 행열
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [16]:
# 튜플을 통해 다차원 배열 생성
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
c = np.zeros((5, 2), dtype="i")  # array와 마찬가지로 dtype 인수를 통해 데이터 형식 지정 가능
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [21]:
# 1행렬 : 모든 값이 1로 초기화된 행열

In [22]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [23]:
# 기존의 다른 배열과 같은 크기의 영행렬/1행렬을 만들고 싶다면? zeros_like() | ones_like()
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [25]:
# 크기가 큰 배열을 초기화하는데 시간이 많이 걸린다. => 특정 값으로 초기화 하지않고 크기만 만들어 놓기 : empty()
g = np.empty((4, 3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# arange() = python에서 range 역할
np.arange(10)  # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(3, 21, 2)  # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [31]:
# linespace / logspace : 선형구간 or 로그 구간을 지정한 구간의 수만큼 반복
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

#### 전치 연산 : Transpose (T)
- 행렬의 행과 열의 위치 및 원소를 서로 바꾸는 것

In [32]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 배열 크기 변경

#### reshape() : 지정하는 크기의 배열로 변경


In [34]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
# 사용하는 원소의 갯수가 정해저 있기 때문에 reshape 명령의 형태 튜플의 원소 중 하나는 -1이라는 숫자로 대체할 수 있다.
# -1을 넣으면 해당 숫자는 다를 값에서 계산되어 사용된다.
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [40]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

#### flatten() / ravel() : 다차원 배열 --> 1차원 배열

In [42]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 차원 증가 : newaxis

In [45]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [48]:
x[np.newaxis]

array([[0, 1, 2, 3, 4]])

In [49]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

### 배열 연결

In [50]:
# 수평적 연결(horizontal stack) : hstack([arr1, arr2, ...]])
# 연결하려는 배열들의 nrow가 같아야 한다.
a1 = np.ones((2, 3))
a1

a2 = np.zeros((2, 2))
a2

np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [51]:
# 수직적 연결(vertical stack) : vstack([arr1, arr2, ...])
# 연결하려는 배열들의 ncol이 같아야한다.
b1 = np.ones((2, 3))
b1

b2 = np.zeros((3, 3))
b2

np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
# 차원적 연결(dimensional stack) : dstack
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [55]:
k = np.arange(48)

In [56]:
len(k)

48

In [57]:
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [58]:
l = k.reshape(2,4,6) #

In [59]:
l

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [66]:
m = l.sum(axis = 0)
m

array([[24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70]])

In [67]:
m.shape

(4, 6)

In [68]:
n = l.sum(axis = 1)
n

array([[ 36,  40,  44,  48,  52,  56],
       [132, 136, 140, 144, 148, 152]])

In [69]:
n.shape

(2, 6)

In [71]:
o = l.sum(axis = 2)
o

array([[ 15,  51,  87, 123],
       [159, 195, 231, 267]])

In [72]:
o.shape

(2, 4)

In [73]:
arr1 = np.random.randint(1,15,(5,3))
arr2 = np.random.randint(15,30,(5,3))
print(arr1)
print(arr2)

[[11  4 10]
 [ 7  3 12]
 [ 8  7  7]
 [ 8 13  3]
 [10 12  9]]
[[20 28 20]
 [21 25 27]
 [26 25 17]
 [26 29 29]
 [27 29 18]]


In [77]:
arr3 = np.stack([arr1, arr2], axis = 0)
arr3

array([[[11,  4, 10],
        [ 7,  3, 12],
        [ 8,  7,  7],
        [ 8, 13,  3],
        [10, 12,  9]],

       [[20, 28, 20],
        [21, 25, 27],
        [26, 25, 17],
        [26, 29, 29],
        [27, 29, 18]]])

In [78]:
arr3 = np.stack([arr1, arr2], axis = 1)
arr3

array([[[11,  4, 10],
        [20, 28, 20]],

       [[ 7,  3, 12],
        [21, 25, 27]],

       [[ 8,  7,  7],
        [26, 25, 17]],

       [[ 8, 13,  3],
        [26, 29, 29]],

       [[10, 12,  9],
        [27, 29, 18]]])

In [79]:
arr3.shape

(5, 2, 3)

In [80]:
# r_ (=hstack) / c_(=vstack)
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]


array([1, 2, 3, 4, 5, 6])

In [81]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [91]:
arr0 = np.zeros((3,3))
arr1 = np.ones((3,2))
arr2 = np.arange(10, 151, 10).reshape(3,5)
arr2

arr3 = np.concatenate([arr0,arr1], axis = 1)
arr4 = np.concatenate([arr3, arr2], axis = 0)
np.tile(arr4, (2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])